name: SKJEMTEFILM
favicon: null
layout_spectrum: 0.50563
typography_spectrum: 0.20872
title: SKJEMTEFILM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090907'
    - '#564437'
    - '#937a64'
    - '#baab8c'
    - '#e8d9ba'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.160760089289397
purpose: []
