name: ANDRE VI ER STOLTE AV
favicon: null
layout_spectrum: 0.50563
typography_spectrum: 0.20872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#343c3f'
    - '#627b7f'
    - '#898a8c'
    - '#4f4f4f'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.160760089289397
purpose: []
